---
- name: 'Common packages installation'
  hosts: all
  sudo: true
  roles:
  - jdk

- name: 'Cassandra DSC nodes installation'
  hosts: all
  sudo: true
  roles:
  - dsc

- name: 'Initializing database'
  hosts: cassandra01
  roles:
  - db

