# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
N = 3
Vagrant.configure(2) do |config|
 (1..N).each do |machine_id|
    config.vm.define "cassandra0#{machine_id}" do |machine|
      machine.vm.hostname = "cassandra0#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.1.#{10+machine_id}"
      if machine_id == N
        config.vm.provision :ansible do |ansible|
          ansible.playbook = "playbook.yml"
          #ansible.inventory_path = "provisioning/hosts"
          ansible.verbose = "vvvv"
          ansible.limit = "all"
        end
      end
    end
 end
 config.vm.box = "ubuntu/trusty64"
 config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.memory = "2048"
  end
end
